library(svgR)
library(tidyverse)
WH<-c(600,400)

# We use 2 tibbles to contain the shapes together with an id
# The id generated by the onNewRow preprocessor applied
# to both rect$id and ellipse$id. In addition, the
# onNewRow preprocessor adds that id to the displaySeq
# In the svg these shapes are set (as symbols) and 
# rendered according to the ordering on displaySeq

# Thus drag and drop of row of displaySeq sets the 
# the z-ordering

# Defined by mouse: edit with care!
ptR<-list(
  rect= tribble(
      ~id,          ~fill,        ~xy,
      'dhntgdem',   '#AEE8B1',    matrix( c(c(108,164)), 2),
      'zfhimecr',   'lightblue',  matrix( c(c(296,21)), 2),
      'ocwjdior',   '#206C85',    matrix( c(c(165,192)), 2),
      'lbbpkvjd',   '#B929CC',    matrix( c(c(146,67)), 2),
      'mrkuwaiz',   '#E4AEE8',    matrix( c(c(266,302)), 2),
      'eiifapod',   '#E8E1AE',    matrix( c(c(506,53)), 2)
  ),
  ellipse= tribble(
      ~id,         ~fill,       ~cxy,
      'viyfiqbw',  'red',       matrix( c(c(362,72)), 2),
      'asduepwi',  'blue',      matrix( c(c(65,149)), 2),
      'nokwucfm',  'blue',      matrix( c(c(474,203)), 2),
      'zlitdkjw',  '#00FF73',   matrix( c(c(474,287)), 2)
  ),
  displayseq= tribble(
      ~id,         ~points,
      'zfhimecr',  matrix(0,2,0),
      'lbbpkvjd',  matrix(0,2,0),
      'asduepwi',  matrix(0,2,0),
      'zlitdkjw',  matrix(0,2,0),
      'mrkuwaiz',  matrix(0,2,0),
      'viyfiqbw',  matrix(0,2,0),
      'ocwjdior',  matrix(0,2,0),
      'dhntgdem',  matrix(0,2,0),
      'nokwucfm',  matrix(0,2,0),
      'eiifapod',  matrix(0,2,0)
  )
)


svgR(wh=WH,
     
    # sets shapes to referenced (but not rendered here)
    pmap(ptR$rect, compose(symbol,rect), wh=c(100,100) ) ,
    pmap(ptR$ellipse, compose(symbol,ellipse), rxy=c(100,50),fill=rrgb()),
    
    # renders the referenced shapes in the tib displaySeq 
    pmap(
        ptR$displayseq, function(id,points){
            use(xlink.href=paste0('#',id))
        } 
    )
)


